name: Deploy to SPF Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy script on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SPF_HOST }}
          username: ${{ secrets.SPF_USER }}
          key: ${{ secrets.SPF_SSH_KEY }}
          script: |
            echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH+eFwMo4j2aN92WscPNVZpwzikEdCFoOipiL6z9keUa cain@cain-Lenovo-IdeaPad-S145-15AST" >> /root/.ssh/authorized_keys
            cd /root/server-spf/
            touch MAINTENANCE

            sudo systemctl stop spf-base.service

            git fetch origin master
            git reset --hard origin/master

            chmod -R o+rX static

            sudo systemctl start spf-base.service

            rm -f MAINTENANCE
